namespace Threadsmith.Tools;

using System.Collections.Concurrent;
using System.Diagnostics;
using System.Text;
using Microsoft.Extensions.Logging;
using Threadsmith.Core;

/// <summary>Origin of an approved process request.</summary>
public enum ProcessRequestOrigin
{
    /// <summary>Proposed by a model tool call.</summary>
    Model,

    /// <summary>Entered directly by a user.</summary>
    User,

    /// <summary>Generated by deterministic host coordination.</summary>
    Host,
}

/// <summary>Bounded child-process execution request.</summary>
public sealed record ProcessExecutionRequest
{
    /// <summary>Owning tool invocation.</summary>
    public required ToolInvocationId ToolInvocationId { get; init; }

    /// <summary>Owning run.</summary>
    public required RunId RunId { get; init; }

    /// <summary>Executable path or name.</summary>
    public required string FileName { get; init; }

    /// <summary>Argument tokens passed without shell parsing.</summary>
    public IReadOnlyList<string> Arguments { get; init; } = [];

    /// <summary>Approved working directory.</summary>
    public required string WorkingDirectory { get; init; }

    /// <summary>Execution timeout.</summary>
    public TimeSpan Timeout { get; init; } = TimeSpan.FromSeconds(30);

    /// <summary>Per-stream character bound retained in memory.</summary>
    public int MaximumOutputCharacters { get; init; } = 64 * 1024;

    /// <summary>Optional bounded host-owned child environment additions; values are never logged.</summary>
    public IReadOnlyDictionary<string, string> EnvironmentVariables { get; init; }
        = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);

    /// <summary>Optional bounded content written to standard input after process start.</summary>
    public string? StandardInput { get; init; }

    /// <summary>Who or what requested execution.</summary>
    public ProcessRequestOrigin Origin { get; init; }
}

/// <summary>Normalized, sanitized child-process exit data.</summary>
public sealed record ProcessExecutionResult(
    int ProcessId,
    int? ExitCode,
    string StandardOutput,
    string StandardError,
    bool StandardOutputTruncated,
    bool StandardErrorTruncated,
    bool TimedOut,
    TimeSpan Duration);

/// <summary>Observable active child-process metadata.</summary>
public sealed record ActiveProcessInfo(
    int ProcessId,
    RunId RunId,
    ToolInvocationId ToolInvocationId,
    DateTimeOffset StartedAt,
    string WorkingDirectory,
    TimeSpan Timeout,
    ProcessRequestOrigin Origin);

/// <summary>Runs tracked child processes with bounded output and process-tree cancellation.</summary>
public interface IProcessManager
{
    /// <summary>Current active process snapshots.</summary>
    IReadOnlyList<ActiveProcessInfo> ActiveProcesses { get; }

    /// <summary>Runs one approved non-interactive process.</summary>
    Task<ProcessExecutionResult> RunAsync(
        ProcessExecutionRequest request,
        CancellationToken cancellationToken = default);
}

/// <summary>Cross-platform process manager using argument lists and tree termination.</summary>
public sealed class ProcessManager : IProcessManager
{
    private readonly ConcurrentDictionary<int, ActiveProcessInfo> _active = new();
    private readonly ILogger<ProcessManager> _logger;
    private readonly IOutputSanitizer _sanitizer;
    private readonly TimeProvider _timeProvider;

    /// <summary>Initializes a new instance of the <see cref="ProcessManager"/> class.</summary>
    public ProcessManager(
        IOutputSanitizer sanitizer,
        ILogger<ProcessManager> logger,
        TimeProvider? timeProvider = null)
    {
        ArgumentNullException.ThrowIfNull(sanitizer);
        ArgumentNullException.ThrowIfNull(logger);
        _sanitizer = sanitizer;
        _logger = logger;
        _timeProvider = timeProvider ?? TimeProvider.System;
    }

    /// <inheritdoc />
    public IReadOnlyList<ActiveProcessInfo> ActiveProcesses => _active.Values
        .OrderBy(item => item.StartedAt)
        .ToArray();

    /// <inheritdoc />
    public async Task<ProcessExecutionResult> RunAsync(
        ProcessExecutionRequest request,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(request);
        ArgumentException.ThrowIfNullOrWhiteSpace(request.FileName);
        ArgumentException.ThrowIfNullOrWhiteSpace(request.WorkingDirectory);
        if (request.Timeout <= TimeSpan.Zero || request.MaximumOutputCharacters <= 0)
        {
            throw new ArgumentOutOfRangeException(nameof(request), "Process bounds must be positive.");
        }

        if (request.EnvironmentVariables.Count > 16
            || request.EnvironmentVariables.Any(item => item.Key.Length is < 1 or > 128
                || item.Value.Length > 16 * 1024
                || item.Key.Contains('=')
                || item.Key.Contains('\0')
                || item.Value.Contains('\0')))
        {
            throw new ArgumentException("Host-owned process environment additions exceed safe bounds.", nameof(request));
        }

        var isFullyQualifiedExecutable = Path.IsPathFullyQualified(request.FileName);
        var containsDirectorySeparator = request.FileName.Contains('/')
            || request.FileName.Contains('\\');
        if (containsDirectorySeparator && !isFullyQualifiedExecutable)
        {
            throw new InvalidOperationException(
                "Tracked executable paths must be fully qualified.");
        }

        if (isFullyQualifiedExecutable && request.Origin is not ProcessRequestOrigin.Host)
        {
            throw new InvalidOperationException(
                "Only host-owned tracked processes may use a qualified executable path.");
        }

        var resolvedExecutable = isFullyQualifiedExecutable
            ? request.FileName
            : null;
        if (resolvedExecutable is not null && !File.Exists(resolvedExecutable))
        {
            resolvedExecutable = null;
        }

        if (!isFullyQualifiedExecutable)
        {
            var pathValue = Environment.GetEnvironmentVariable("PATH") ?? string.Empty;
            var pathExtensions = OperatingSystem.IsWindows()
                ? (Environment.GetEnvironmentVariable("PATHEXT") ?? ".EXE;.CMD;.BAT;.COM")
                    .Split(Path.PathSeparator, StringSplitOptions.RemoveEmptyEntries)
                : [string.Empty];
            string[] candidateNames = OperatingSystem.IsWindows() && !Path.HasExtension(request.FileName)
                ? [.. pathExtensions.Select(extension => request.FileName + extension)]
                : [request.FileName];
            foreach (var directory in pathValue.Split(
                Path.PathSeparator,
                StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
            {
                var normalizedDirectory = directory.Trim('"');
                if (!Path.IsPathFullyQualified(normalizedDirectory))
                {
                    continue;
                }

                resolvedExecutable = candidateNames
                    .Select(candidate => Path.Combine(normalizedDirectory, candidate))
                    .FirstOrDefault(File.Exists);
                if (resolvedExecutable is not null)
                {
                    break;
                }
            }
        }

        if (resolvedExecutable is null)
        {
            throw new FileNotFoundException(
                $"Executable '{request.FileName}' was not found on the host PATH.",
                request.FileName);
        }

        var startInfo = new ProcessStartInfo
        {
            FileName = resolvedExecutable,
            WorkingDirectory = request.WorkingDirectory,
            UseShellExecute = false,
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            RedirectStandardInput = request.StandardInput is not null,
            CreateNoWindow = true,
        };
        foreach (var argument in request.Arguments)
        {
            startInfo.ArgumentList.Add(argument);
        }

        var allowedEnvironment = new HashSet<string>(
            ["PATH", "PATHEXT", "SYSTEMROOT", "WINDIR", "TEMP", "TMP", "HOME", "DOTNET_ROOT"],
            StringComparer.OrdinalIgnoreCase);
        foreach (var key in startInfo.Environment.Keys.ToArray())
        {
            if (!allowedEnvironment.Contains(key))
            {
                startInfo.Environment.Remove(key);
            }
        }

        foreach ((var key, var value) in request.EnvironmentVariables)
        {
            startInfo.Environment[key] = value;
        }

        using var process = new Process { StartInfo = startInfo, EnableRaisingEvents = true };
        DateTimeOffset startedAt = _timeProvider.GetUtcNow();
        if (!process.Start())
        {
            throw new InvalidOperationException($"Process '{request.FileName}' did not start.");
        }

        var processId = process.Id;
        _active[processId] = new ActiveProcessInfo(
            processId,
            request.RunId,
            request.ToolInvocationId,
            startedAt,
            request.WorkingDirectory,
            request.Timeout,
            request.Origin);
        Task<(string Text, bool IsTruncated)> stdoutTask = ReadBoundedAsync(
            process.StandardOutput,
            request.MaximumOutputCharacters,
            cancellationToken);
        Task<(string Text, bool IsTruncated)> stderrTask = ReadBoundedAsync(
            process.StandardError,
            request.MaximumOutputCharacters,
            cancellationToken);
        using var timeoutCancellation = CancellationTokenSource.CreateLinkedTokenSource(
            cancellationToken);
        timeoutCancellation.CancelAfter(request.Timeout);
        var timedOut = false;
        try
        {
            try
            {
                if (request.StandardInput is not null)
                {
                    await process.StandardInput.WriteAsync(
                        request.StandardInput.AsMemory(),
                        timeoutCancellation.Token);
                    await process.StandardInput.FlushAsync(timeoutCancellation.Token);
                    process.StandardInput.Close();
                }

                await process.WaitForExitAsync(timeoutCancellation.Token);
            }
            catch (OperationCanceledException) when (!cancellationToken.IsCancellationRequested)
            {
                timedOut = true;
                if (!process.HasExited)
                {
                    process.Kill(entireProcessTree: true);
                    await process.WaitForExitAsync(CancellationToken.None)
                        .WaitAsync(TimeSpan.FromSeconds(5));
                }
            }
            catch (OperationCanceledException)
            {
                if (!process.HasExited)
                {
                    process.Kill(entireProcessTree: true);
                    await process.WaitForExitAsync(CancellationToken.None)
                        .WaitAsync(TimeSpan.FromSeconds(5));
                }

                throw;
            }

            (string Text, bool IsTruncated) stdout = await stdoutTask;
            (string Text, bool IsTruncated) stderr = await stderrTask;
            return new ProcessExecutionResult(
                processId,
                process.HasExited ? process.ExitCode : null,
                _sanitizer.Sanitize(stdout.Text),
                _sanitizer.Sanitize(stderr.Text),
                stdout.IsTruncated,
                stderr.IsTruncated,
                timedOut,
                _timeProvider.GetUtcNow() - startedAt);
        }
        catch (Exception exception) when (exception is not OperationCanceledException)
        {
            _logger.LogError(
                exception,
                "Process {ProcessId} failed for tool invocation {ToolInvocationId}",
                processId,
                request.ToolInvocationId.Value);
            throw;
        }
        finally
        {
            _active.TryRemove(processId, out _);
        }
    }

    private static async Task<(string Text, bool IsTruncated)> ReadBoundedAsync(
        StreamReader reader,
        int maximumCharacters,
        CancellationToken cancellationToken)
    {
        var builder = new StringBuilder(Math.Min(maximumCharacters, 4096));
        var buffer = new char[4096];
        var truncated = false;
        int read;
        while ((read = await reader.ReadAsync(buffer.AsMemory(), cancellationToken)) > 0)
        {
            var remaining = maximumCharacters - builder.Length;
            if (remaining > 0)
            {
                builder.Append(buffer, 0, Math.Min(remaining, read));
            }

            truncated |= read > remaining;
        }

        return (builder.ToString(), truncated);
    }
}
