namespace Threadsmith.DotNet;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

/// <summary>Classifies generated C# source using path conventions and bounded comment-banner inspection.</summary>
internal static class CodeExploreGeneratedSourceClassifier
{
    private const int HeaderScanCharacters = 8192;
    private const int HeaderScanLines = 60;

    /// <summary>Returns whether a path follows a common generated C# convention.</summary>
    public static bool IsGeneratedPath(string path)
    {
        var normalized = path.Replace('\\', '/');
        return normalized.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase)
            || normalized.EndsWith(".generated.cs", StringComparison.OrdinalIgnoreCase)
            || normalized.EndsWith(".designer.cs", StringComparison.OrdinalIgnoreCase)
            || normalized.EndsWith("grpc.cs", StringComparison.OrdinalIgnoreCase)
            || normalized.Contains("/obj/", StringComparison.OrdinalIgnoreCase);
    }

    /// <summary>Returns whether the bounded source header contains a recognized generator banner.</summary>
    public static bool HasGeneratedHeader(SyntaxNode root)
    {
        if (root.SyntaxTree is not { } syntaxTree)
        {
            return false;
        }

        foreach (var trivia in root.DescendantTrivia(descendIntoTrivia: false))
        {
            if (trivia.SpanStart >= HeaderScanCharacters
                || syntaxTree.GetLineSpan(trivia.Span).StartLinePosition.Line >= HeaderScanLines)
            {
                break;
            }

            if (!IsComment(trivia))
            {
                continue;
            }

            var text = trivia.ToString();
            if (text.Contains("generat", StringComparison.OrdinalIgnoreCase)
                && IsGeneratedBanner(text))
            {
                return true;
            }
        }

        return false;
    }

    private static bool IsComment(SyntaxTrivia trivia)
    {
        return trivia.IsKind(SyntaxKind.SingleLineCommentTrivia)
            || trivia.IsKind(SyntaxKind.MultiLineCommentTrivia)
            || trivia.IsKind(SyntaxKind.SingleLineDocumentationCommentTrivia)
            || trivia.IsKind(SyntaxKind.MultiLineDocumentationCommentTrivia);
    }

    private static bool IsGeneratedBanner(string comment)
    {
        var normalized = comment.ToLowerInvariant();
        var warnsAgainstEditing = normalized.Contains("do not edit", StringComparison.Ordinal)
            || normalized.Contains("do not modify", StringComparison.Ordinal)
            || normalized.Contains("do not change", StringComparison.Ordinal);
        if (normalized.Contains("code generated", StringComparison.Ordinal) && warnsAgainstEditing)
        {
            return true;
        }

        var namesGeneratorRelationship = normalized.Contains("generated by", StringComparison.Ordinal)
            || normalized.Contains("generated from", StringComparison.Ordinal)
            || normalized.Contains("generated with", StringComparison.Ordinal);
        if (namesGeneratorRelationship && warnsAgainstEditing)
        {
            return true;
        }

        if (normalized.Contains("@generated", StringComparison.Ordinal)
            || normalized.Contains("<auto-generated", StringComparison.Ordinal)
            || normalized.Contains("<autogenerated", StringComparison.Ordinal)
            || normalized.Contains("automatically generated by", StringComparison.Ordinal)
            || normalized.Contains("auto-generated by", StringComparison.Ordinal)
            || normalized.Contains("autogenerated by", StringComparison.Ordinal))
        {
            return true;
        }

        var selfDeclaresGenerated = normalized.Contains("this file is generated", StringComparison.Ordinal)
            || normalized.Contains("this file was generated", StringComparison.Ordinal)
            || normalized.Contains("this class is generated", StringComparison.Ordinal)
            || normalized.Contains("this class was generated", StringComparison.Ordinal)
            || normalized.Contains("this code is generated", StringComparison.Ordinal)
            || normalized.Contains("this code was generated", StringComparison.Ordinal)
            || normalized.Contains("this module is generated", StringComparison.Ordinal)
            || normalized.Contains("this module was generated", StringComparison.Ordinal);
        return selfDeclaresGenerated
            || (warnsAgainstEditing
                && (normalized.Contains("generated file", StringComparison.Ordinal)
                    || normalized.Contains("generated code", StringComparison.Ordinal)));
    }
}
